In [28]:
"""
Created on: Wed. 5 Oct. 2022
Updated on: Thu. 13 Oct. 2022
Updated on: Fri. 14 Oct. 2022
Updated on: Mon. 31 Oct. 2022
Updated on: Mon. 14 Nov. 2022
Updated on: Wed. 4 Jan. 2023
Author: MÃ©lina Verger

Prepare the chosen data set until train-test split.
Choose the sensitive fatures.
Select the classifier models.
"""

# To exit script
from sys import exit

# For data manipulation
import pandas as pd
pd.set_option('display.max_columns', None)

# To make the train-test split
from sklearn.model_selection import train_test_split

# To save the variables
import pickle

# To interact with the operating system
import os

# ML models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import ComplementNB, MultinomialNB

## Load a numerical and scaled data set

In [29]:
# Load the chosen data set (num and scaled)

user_response1 = input("Do you want to work with stInfo, stAll or stClick set (scaled)? (Write either stInfo, stAll or stClick.)")
if user_response1 == "stInfo":
    data_num_scaled = pd.read_csv("../data/studentInfo_num_scaled.csv")
elif user_response1 == "stAll":
    data_num_scaled = pd.read_csv("../data/studentAll_num_scaled.csv")
elif user_response1 == "stClick":
    data_num_scaled = pd.read_csv("../data/studentClick_num_scaled.csv")
else:
    print("Invalid choice.")
    exit()

print(user_response1)

stClick

In [30]:
DATA = user_response1
pickle.dump(DATA, open("../data/DATA", "wb"))

## Reduction data set to course "BBB"

In [31]:
# Choose a course

user_response3 = input("Do you want to reduce the data set to the course 'BBB'? (y/n)")
if user_response3 == 'y':
    data_num_scaled_reduced = data_num_scaled.loc[data_num_scaled["code_module_BBB"] == 1]
    print("Data reduction to course 'BBB'.", flush=True)
elif user_response3 == 'n':
    data_num_scaled_reduced = data_num_scaled
    print("No data set reduction to course 'BBB'.", flush=True)
else:
    print("Invalid choice.")
    exit()

user_response3bis = input("Do you want to reduce the data set to the course 'FFF'? (y/n)")
if user_response3bis == 'y':
    data_num_scaled_reduced = data_num_scaled.loc[data_num_scaled["code_module_FFF"] == 1]
    print("Data reduction to course 'FFF'.", flush=True)
elif user_response3bis == 'n':
    data_num_scaled_reduced = data_num_scaled
    print("No data set reduction to course 'FFF'.", flush=True)
else:
    print("Invalid choice.")
    exit()

Data reduction to course 'BBB'.
No data set reduction to course 'FFF'.

In [32]:
data_num_scaled

,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,sum_click,final_result,code_module_AAA,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013B,code_presentation_2013J,code_presentation_2014B,code_presentation_2014J,region_East Anglian Region,region_East Midlands Region,region_Ireland,region_London Region,region_North Region,region_North Western Region,region_Scotland,region_South East Region,region_South Region,region_South West Region,region_Wales,region_West Midlands Region,region_Yorkshire Region
0,1.0,0.75,0.0,1.0,0.0,0.0,0.35,0.038653,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.75,1.0,0.5,0.0,0.0,0.05,0.059408,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.50,0.0,0.5,0.0,0.0,0.05,0.089361,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.25,0.0,0.0,0.0,0.0,0.05,0.042796,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.50,0.0,0.5,0.0,0.0,0.05,0.101251,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19959,0.0,0.50,0.0,0.0,1.0,0.0,0.00,0.019679,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19960,0.0,0.25,1.0,0.0,0.0,0.0,0.00,0.001657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19961,0.0,0.25,1.0,0.5,0.0,0.0,0.00,0.036954,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19962,0.0,0.50,1.0,0.0,1.0,0.0,0.00,0.012884,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19963,0.0,0.75,0.0,0.5,0.0,0.0,0.00,0.025478,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
data_num_scaled_reduced.shape

(19964, 33)

In [34]:
# Keep the interesting features

if user_response1 == "stInfo":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "final_result"]]

if user_response1 == "stAll":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "sum_click", "weighted_score", "final_result"]]

if user_response1 == "stClick":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "sum_click", "final_result"]]

In [35]:
data_num_scaled_reduced.shape

(19964, 9)

In [36]:
data_num_scaled_reduced

,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,sum_click,final_result
0,1.0,0.75,0.0,1.0,0.0,0.0,0.35,0.038653,1.0
1,0.0,0.75,1.0,0.5,0.0,0.0,0.05,0.059408,1.0
2,0.0,0.50,0.0,0.5,0.0,0.0,0.05,0.089361,1.0
3,0.0,0.25,0.0,0.0,0.0,0.0,0.05,0.042796,1.0
4,1.0,0.50,0.0,0.5,0.0,0.0,0.05,0.101251,1.0
...,...,...,...,...,...,...,...,...,...
19959,0.0,0.50,0.0,0.0,1.0,0.0,0.00,0.019679,1.0
19960,0.0,0.25,1.0,0.0,0.0,0.0,0.00,0.001657,0.0
19961,0.0,0.25,1.0,0.5,0.0,0.0,0.00,0.036954,1.0
19962,0.0,0.50,1.0,0.0,1.0,0.0,0.00,0.012884,1.0
19963,0.0,0.75,0.0,0.5,0.0,0.0,0.00,0.025478,1.0

In [37]:
# Gender imbalance

round(data_num_scaled_reduced["gender"].value_counts()[0] / (data_num_scaled_reduced["gender"].value_counts()[0] + data_num_scaled_reduced["gender"].value_counts()[1]) * 100, 2)

47.85

## Machine learning (preparation)

### X-y split

In [38]:
X = data_num_scaled_reduced.drop(columns="final_result")
y = data_num_scaled_reduced["final_result"]

In [39]:
# Positive class imbalance

round(y.value_counts()[1] / (y.value_counts()[1] + y.value_counts()[0]) * 100, 2)

68.41

### Train-test split

In [40]:
# Choose a train-test split

user_response2 = input("Do you want 70-30 or 80-20 train-test split? (Write either 7030 or 8020.)")
if user_response2 == "7030" or user_response2 == "8020":
    SPLIT = user_response2
else:
    print("Invalid choice.")
    exit()

print(user_response2)

7030

In [41]:
pickle.dump(SPLIT, open("../data/SPLIT", "wb"))

In [42]:
if SPLIT == "7030":
    ratio = 0.30
elif SPLIT == "8020":
    ratio = 0.20

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=0, stratify=y, shuffle=True)

In [44]:
pd.DataFrame(X_train).to_csv("../data/X_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(X_test).to_csv("../data/X_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_train).to_csv("../data/y_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_test).to_csv("../data/y_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)

In [45]:
print(X_train.shape)
print(X_test.shape)

(13974, 8)
(5990, 8)

## Choose the sensitive features

In [46]:
user_response4 = int(input(f"How many sensitive features do you consider into {list(X_train.columns)}? (Write a number greater than 0.)"))

L_sensitive_features = list()

if user_response4 == 1:
    feature_name = input(f"Write a feature name belonging to {list(X_train.columns)}: ")
    if feature_name in X_train.columns:
        L_sensitive_features.append(feature_name)
    else:
        print("Invalid name.")
        exit()

else:
    for i in range(user_response4):
        feature_name = input(f"Write the feature name #{i + 1} belonging to {list(X_train.columns)}: ")
        if feature_name in X_train.columns:
            L_sensitive_features.append(feature_name)
        else:
            print("Invalid name.")
            exit()

print("Sensitive features: ", L_sensitive_features)

Sensitive features:  ['gender', 'imd_band', 'disability']

In [47]:
SFEATURES = L_sensitive_features
pickle.dump(SFEATURES, open("../data/SFEATURES", "wb"))

## Select the classifier models

In [48]:
if not os.path.exists("../models"):
    os.mkdir("models")
else:
    print("The folder '../models' already exists." )

The folder '../models' already exists.

In [49]:
model_names = []
models = dict()

user_response_lr = input("Do you want to use a logistic regression classifier (LR)? (y/n)")
if user_response_lr == "y":
    clf_lr = LogisticRegression(random_state=0)
    model_names.append("a logistic regression")
    models["clf_lr"] = clf_lr

user_response_kn = input("Do you want to use a k-nearest neighbors classifier (KN)? (y/n)")
if user_response_kn == "y":
    clf_kn = KNeighborsClassifier()
    model_names.append("a k-nearest neighbors")
    models["clf_kn"] = clf_kn

user_response_dt = input("Do you want to use a decision tree classifier (DT)? (y/n)")
if user_response_dt == "y":
    clf_dt = DecisionTreeClassifier(random_state=0)
    model_names.append("a decision tree")
    models["clf_dt"] = clf_dt

user_response_rf = input("Do you want to use a random forest classifier (RF)? (y/n)")
if user_response_rf == "y":
    clf_rf = RandomForestClassifier(random_state=0)
    model_names.append("a random forest")
    models["clf_rf"] = clf_rf

user_response_svc = input("Do you want to use a linear support vector classifier (SVC)? (y/n)")
if user_response_svc == "y":
    clf_svc = LinearSVC(random_state=0)
    model_names.append("a linear support vector")
    models["clf_svc"] = clf_svc

user_response_cnb = input("Do you want to use a complement naive bayes classifier (CNB)? (y/n)")
if user_response_cnb == "y":
    clf_cnb = ComplementNB()
    model_names.append("a complement naive bayes")
    models["clf_cnb"] = clf_cnb

user_response_mnb = input("Do you want to use a multinomial naive bayes classifier (MNB)? (y/n)")
if user_response_mnb == "y":
    clf_mnb = MultinomialNB()
    model_names.append("a multinomial naive bayes")
    models["clf_mnb"] = clf_mnb

if len(model_names) == 0:
    print("You chose none of these models. Please implement one.")
else:
    print(f"You chose {', '.join(model_names)} classifiers.", flush=True)

You chose a logistic regression, a decision tree, a complement naive bayes, a multinomial naive bayes classifiers.

In [50]:
# Train and save trained models

for mod_name in models:
    mod = models[mod_name]  # the model object
    models[mod_name] = mod.fit(X_train, y_train)  # update with trained models
    

MODELS = models
pickle.dump(MODELS, open("../data/MODELS", "wb"))

## Execute automatically

In [51]:
!jupyter nbconvert --to notebook --execute eval_performance.ipynb

[NbConvertApp] Converting notebook eval_performance.ipynb to notebook
[NbConvertApp] Writing 51723 bytes to eval_performance.nbconvert.ipynb

In [52]:
#!jupyter nbconvert --to notebook --execute eval_fairness.ipynb

In [53]:
!jupyter nbconvert --to notebook --execute distrib_plots.ipynb

[NbConvertApp] Converting notebook distrib_plots.ipynb to notebook
Traceback (most recent call last):
  File "/Users/melinaverger/Desktop/exp2/env/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 147, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 342, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 91, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 112, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for sensfeat in SFEATURES:

    if sensfeat == "gender":
        color_gp_1 = "darkorange"
        color_gp_0 = "blue"
        #color_gp_1 = "mediumaquamarine"
        #color_gp_0 = "lightcoral"
    elif sensfeat == "imd_band":
        color_gp_1 = "gold"
        color_gp_0 = "dimgray"
    elif sensfeat == "disability":
        color_gp_1 = "mediumpurple"
        color_gp_0 = "lightskyblue"


    for mod_name in models:  # except svc model because no probability outputs

        if mod_name == "clf_lr":
            model_name = "Logistic regression"
        elif mod_name == "clf_kn":
            model_name = "K-nearest neighbors"
        elif mod_name == "clf_dt":
            model_name = "Decision tree"
        elif mod_name == "clf_rf":
            model_name = "Random forest"
        else:
            print("Invalid model.")
            exit()

        fig, axes = plt.subplots(1, 3, figsize=(12, 4), constrained_layout=True)
        fig.supxlabel("Prediction probabilities  [0 ; 1]", fontsize=12)
        # plot the 2 y_pred_{sensitive feature for group 0/1} separately
        ax0 = sns.histplot(ax=axes[0], data=models[mod_name].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "1"])[:, 1], kde=False, stat="proportion", color=color_gp_1, bins=np.linspace(0,1,101))
        ax0.set_ylim(0, 0.3)
        ax0.set_xlim(0, 1)
        ax0.set_ylabel("Proportion  [0 ; 1]", fontsize=12)
        ax1 = sns.histplot(ax=axes[1], data=models[mod_name].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "0"])[:, 0], kde=False, stat="proportion", color=color_gp_0, bins=np.linspace(0,1,101))
        ax1.set_ylim(0, 0.3)
        ax1.set_xlim(0, 1)
        ax1.set_yticklabels([]) # turn off y ticks labels
        ax1.yaxis.set_visible(False)
        # plot the 2 DDPs on the same graph
        ax2 = sns.kdeplot(ax=axes[2], data=models[mod_name].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "1"])[:, 1], color=color_gp_1, label=sensfeat + ": 1")
        ax2 = sns.kdeplot(ax=axes[2], data=models[mod_name].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "0"])[:, 0], color=color_gp_0, label=sensfeat + ": 0")
        ax2.set_ylabel("Density  > 0", fontsize=12)
        ax2.set_xlim(0, 1)

        plt.legend(loc="upper left")
        ax1.set_title(f"[{DATA} {SPLIT}] {model_name}", loc="center", fontsize=14)

        for ax in axes:
            obj = ax.get_children()
            pickle.dump(obj, open("../zones/kdes_" + mod_name + "_" + sensfeat + ".pickle", "wb"))
------------------

An exception has occurred, use %tb to see the full traceback.

SystemExit

SystemExit:

In [54]:
!jupyter nbconvert --to notebook --execute distrib_measure.ipynb

[NbConvertApp] Converting notebook distrib_measure.ipynb to notebook
Traceback (most recent call last):
  File "/Users/melinaverger/Desktop/exp2/env/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 147, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 342, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 91, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 112, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/melinaverger/Desktop/exp2/env/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dict_subsets_PP = dict()

for mod_names in models:

    if mod_names == "clf_lr":
        modl = "lr"
    elif mod_names == "clf_kn":
        modl = "kn"
    elif mod_names == "clf_dt":
        modl = "dt"
    elif mod_names == "clf_rf":
        modl = "rf"
    else:
        print("Invalid model.")
        exit()

    # y_PP for X_test_{sensitive feature and group 1/0}
    for sensfeat in SFEATURES:
        dict_subsets_PP["y" + "_PP_" + modl + "_" + sensfeat + "_" + "1"] = models[mod_names].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "1"])[:, 1]  # [:, 1] because propa of being in the class 1
        dict_subsets_PP["y" + "_PP_" + modl + "_" + sensfeat + "_" + "0"] = models[mod_names].predict_proba(dict_subsets_test["X"+ "_test_" + sensfeat + "_"+ "0"])[:, 0]  # [:, 1] because propa of being in the class 0
------------------

An exception has occurred, use %tb to see the full traceback.

SystemExit

SystemExit: