In [1]:
"""
Created on: Wed. 5 Oct. 2022
Updated on: Thu. 13 Oct. 2022
Updated on: Fri. 14 Oct. 2022
Updated on: Mon. 31 Oct. 2022
Updated on: Mon. 14 Nov. 2022
Author: MÃ©lina Verger

Prepare the chosen data set until train-test split.
Choose the sensitive fatures.
Select the classifier models.
"""

# To exit script
from sys import exit

# For data manipulation
import pandas as pd
pd.set_option('display.max_columns', None)

# To make the train-test split
from sklearn.model_selection import train_test_split

# To save the variables
import pickle

# To interact with the operating system
import os

# ML models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

## Load a numerical and scaled data set

In [2]:
# Load the chosen data set (num and scaled)

user_response1 = input("Do you want to work with stInfo, stAll or stClick set (scaled)? (Write either stInfo, stAll or stClick.)")
if user_response1 == "stInfo":
    data_num_scaled = pd.read_csv("../data/studentInfo_num_scaled.csv")
elif user_response1 == "stAll":
    data_num_scaled = pd.read_csv("../data/studentAll_num_scaled.csv")
elif user_response1 == "stClick":
    data_num_scaled = pd.read_csv("../data/studentClick_num_scaled.csv")
else:
    print("Invalid choice.")
    exit()

In [3]:
DATA = user_response1
pickle.dump(DATA, open("../data/DATA", "wb"))

## Reduction data set to course "BBB"

In [4]:
# Choose a course

user_response3 = input("Do you want to reduce the data set to the course 'BBB'? (y/n)")
if user_response3 == 'y':
    data_num_scaled_reduced = data_num_scaled.loc[data_num_scaled["code_module_BBB"] == 1]
elif user_response3 == 'n':
    data_num_scaled_reduced = data_num_scaled
    print("No data set reduction.")
else:
    print("Invalid choice.")
    exit()

In [5]:
data_num_scaled

,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,sum_click,final_result,code_module_AAA,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013B,code_presentation_2013J,code_presentation_2014B,code_presentation_2014J,region_East Anglian Region,region_East Midlands Region,region_Ireland,region_London Region,region_North Region,region_North Western Region,region_Scotland,region_South East Region,region_South Region,region_South West Region,region_Wales,region_West Midlands Region,region_Yorkshire Region
0,1.0,0.75,0.0,1.0,0.0,0.0,0.35,0.038653,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.75,1.0,0.5,0.0,0.0,0.05,0.059408,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.50,0.0,0.5,0.0,0.0,0.05,0.089361,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.25,0.0,0.0,0.0,0.0,0.05,0.042796,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.50,0.0,0.5,0.0,0.0,0.05,0.101251,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19959,0.0,0.50,0.0,0.0,1.0,0.0,0.00,0.019679,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19960,0.0,0.25,1.0,0.0,0.0,0.0,0.00,0.001657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19961,0.0,0.25,1.0,0.5,0.0,0.0,0.00,0.036954,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19962,0.0,0.50,1.0,0.0,1.0,0.0,0.00,0.012884,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19963,0.0,0.75,0.0,0.5,0.0,0.0,0.00,0.025478,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [6]:
data_num_scaled_reduced.shape

(5299, 33)

In [7]:
# Keep the interesting features

if user_response1 == "stInfo":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "final_result"]]

if user_response1 == "stAll":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "sum_click", "weighted_score", "final_result"]]

if user_response1 == "stClick":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "sum_click", "final_result"]]

In [8]:
data_num_scaled_reduced.shape

(5299, 9)

In [9]:
data_num_scaled_reduced

,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,sum_click,final_result
599,0.0,0.25,1.0,0.0,0.0,0.333333,0.050,0.006629,0.0
600,0.0,0.25,1.0,0.0,0.0,0.000000,0.150,0.106098,1.0
601,1.0,0.25,0.0,0.0,0.0,0.000000,0.150,0.079253,0.0
602,1.0,0.50,1.0,0.5,0.0,0.000000,0.050,0.244635,1.0
603,0.0,0.50,1.0,0.5,0.0,0.333333,0.150,0.029207,1.0
...,...,...,...,...,...,...,...,...,...
5893,0.0,0.75,1.0,0.5,0.0,0.000000,0.050,0.031941,1.0
5894,0.0,0.75,0.0,0.5,0.0,0.000000,0.075,0.099718,1.0
5895,0.0,0.25,0.0,0.5,1.0,0.000000,0.150,0.056674,1.0
5896,0.0,0.25,0.0,0.5,0.0,0.000000,0.050,0.029663,0.0
5897,0.0,0.75,1.0,0.0,0.0,0.000000,0.150,0.025023,1.0

In [10]:
# Gender imbalance

round(data_num_scaled_reduced["gender"].value_counts()[0] / (data_num_scaled_reduced["gender"].value_counts()[0] + data_num_scaled_reduced["gender"].value_counts()[1]) * 100, 2)

88.39

## Machine learning (preparation)

### X-y split

In [11]:
X = data_num_scaled_reduced.drop(columns="final_result")
y = data_num_scaled_reduced["final_result"]

In [12]:
# Positive class imbalance

round(y.value_counts()[1] / (y.value_counts()[1] + y.value_counts()[0]) * 100, 2)

69.82

### Train-test split

In [13]:
# Choose a train-test split

user_response2 = input("Do you want 70-30 or 80-20 train-test split? (Write either 7030 or 8020.)")
if user_response2 == "7030" or user_response2 == "8020":
    SPLIT = user_response2
else:
    print("Invalid choice.")
    exit()

In [14]:
pickle.dump(SPLIT, open("../data/SPLIT", "wb"))

In [15]:
if SPLIT == "7030":
    ratio = 0.30
elif SPLIT == "8020":
    ratio = 0.20

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=0, stratify=y, shuffle=True)

In [17]:
pd.DataFrame(X_train).to_csv("../data/X_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(X_test).to_csv("../data/X_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_train).to_csv("../data/y_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_test).to_csv("../data/y_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)

In [18]:
print(X_train.shape)
print(X_test.shape)

(3709, 8)
(1590, 8)

## Choose the sensitive features

In [19]:
user_response4 = int(input(f"How many sensitive features do you consider into {list(X_train.columns)}? (Write a number greater than 0.)"))

L_sensitive_features = list()

if user_response4 == 1:
    feature_name = input(f"Write a feature name belonging to {list(X_train.columns)}: ")
    if feature_name in X_train.columns:
        L_sensitive_features.append(feature_name)
    else:
        print("Invalid name.")
        exit()

else:
    for i in range(user_response4):
        feature_name = input(f"Write the feature name #{i + 1} belonging to {list(X_train.columns)}: ")
        if feature_name in X_train.columns:
            L_sensitive_features.append(feature_name)
        else:
            print("Invalid name.")
            exit()

In [20]:
SFEATURES = L_sensitive_features
pickle.dump(SFEATURES, open("../data/SFEATURES", "wb"))

## Select the classifier models

In [21]:
if not os.path.exists("../models"):
    os.mkdir("models")
else:
    print("The folder '../models' already exists." )

The folder '../models' already exists.

In [22]:
model_names = []
models = dict()

user_response_lr = input("Do you want to use a logistic regression classifier (LR)? (y/n)")
if user_response_lr == "y":
    clf_lr = LogisticRegression(random_state=0)
    model_names.append("a logistic regression")
    models["clf_lr"] = clf_lr

user_response_kn = input("Do you want to use a k-nearest neighbors classifier (KN)? (y/n)")
if user_response_kn == "y":
    clf_kn = KNeighborsClassifier()
    model_names.append("a k-nearest neighbors")
    models["clf_kn"] = clf_kn

user_response_dt = input("Do you want to use a decision tree classifier (DT)? (y/n)")
if user_response_dt == "y":
    clf_dt = DecisionTreeClassifier(random_state=0)
    model_names.append("a decision tree")
    models["clf_dt"] = clf_dt

user_response_rf = input("Do you want to use a random forest classifier (RF)? (y/n)")
if user_response_rf == "y":
    clf_rf = RandomForestClassifier(random_state=0)
    model_names.append("a random forest")
    models["clf_rf"] = clf_rf

user_response_svc = input("Do you want to use a linear support vector classifier (SVC)? (y/n)")
if user_response_svc == "y":
    clf_svc = LinearSVC(random_state=0)
    model_names.append("a linear support vector")
    models["clf_svc"] = clf_svc

if len(model_names) == 0:
    print("You chose none of these models. Please implement one.")
else:
    print(f"You chose {', '.join(model_names)} classifiers.")

You chose a logistic regression, a k-nearest neighbors, a decision tree classifiers.

In [23]:
# Train and save trained models

for mod_name in models:
    mod = models[mod_name]  # the model object
    models[mod_name] = mod.fit(X_train, y_train)  # update with trained models
    

MODELS = models
pickle.dump(MODELS, open("../data/MODELS", "wb"))

## Execute automatically

In [24]:
!jupyter nbconvert --to notebook --execute eval_performance.ipynb

[NbConvertApp] Converting notebook eval_performance.ipynb to notebook
[NbConvertApp] Writing 43351 bytes to eval_performance.nbconvert.ipynb

In [25]:
#!jupyter nbconvert --to notebook --execute eval_fairness.ipynb

In [26]:
!jupyter nbconvert --to notebook --execute distrib_plots.ipynb

[NbConvertApp] Converting notebook distrib_plots.ipynb to notebook
[NbConvertApp] Writing 368411 bytes to distrib_plots.nbconvert.ipynb

In [27]:
!jupyter nbconvert --to notebook --execute distrib_measure.ipynb

[NbConvertApp] Converting notebook distrib_measure.ipynb to notebook
[NbConvertApp] Writing 11274 bytes to distrib_measure.nbconvert.ipynb