In [55]:
"""
Created on: Wed. 5 Oct. 2022
Author: MÃ©lina Verger

Prepare the chosen data set until train-test split.
"""

# To exit script
from sys import exit

# For data manipulation
import pandas as pd
pd.set_option('display.max_columns', None)

# To make the train-test split
from sklearn.model_selection import train_test_split

# To save the variables
import pickle

## Load a numerical and scaled data set

In [56]:
# Load the chosen data set (num and scaled)

user_response1 = input("Do you want to work with stInfo or stAll set (scaled)? (Write either stInfo or stAll.)")
if user_response1 == "stInfo":
    data_num_scaled = pd.read_csv("../data/studentInfo_num_scaled.csv")
elif user_response1 == "stAll":
    data_num_scaled = pd.read_csv("../data/studentAll_num_scaled.csv")
else:
    print("Invalid choice.")
    exit()

In [57]:
DATA = user_response1
pickle.dump(DATA, open("../data/DATA", "wb"))

## Reduction data set to course "BBB"

In [58]:
# Choose a course

user_response3 = input("Do you want to reduce the data set to the course 'BBB'? (y/n)")
if user_response3 == 'y':
    data_num_scaled_reduced = data_num_scaled.loc[data_num_scaled["code_module_BBB"] == 1]
elif user_response3 == 'n':
    data_num_scaled_reduced = data_num_scaled
    print("No data set reduction.")
else:
    print("Invalid choice.")
    exit()

In [59]:
data_num_scaled

,gender,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,code_module_AAA,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013B,code_presentation_2013J,code_presentation_2014B,code_presentation_2014J,region_East Anglian Region,region_East Midlands Region,region_Ireland,region_London Region,region_North Region,region_North Western Region,region_Scotland,region_South East Region,region_South Region,region_South West Region,region_Wales,region_West Midlands Region,region_Yorkshire Region
0,1.0,0.75,0.0,1.0,0.0,0.35,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.75,1.0,0.5,0.0,0.05,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.50,0.0,0.5,0.0,0.05,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.25,0.0,0.0,0.0,0.05,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.50,0.0,0.5,0.0,0.05,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17800,0.0,0.25,1.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17801,0.0,0.25,1.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
17802,0.0,0.25,0.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17803,0.0,0.25,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17804,0.0,0.50,1.0,0.0,0.0,0.00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [60]:
data_num_scaled_reduced.shape

(4784, 32)

In [61]:
# Keep the interesting features

if user_response1 == "stInfo":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "final_result"]]

if user_response1 == "stAll":
    data_num_scaled_reduced = data_num_scaled_reduced[["gender", "highest_education", "imd_band", "age_band",  "disability", "num_of_prev_attempts", "studied_credits", "sum_click", "weighted_score", "final_result"]]

In [62]:
data_num_scaled_reduced.shape

(4784, 8)

In [63]:
data_num_scaled_reduced

,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,final_result
558,0.0,0.25,1.0,0.0,0.0,0.333333,0.050,0.0
559,0.0,0.25,1.0,0.0,0.0,0.000000,0.150,1.0
560,1.0,0.25,0.0,0.0,0.0,0.000000,0.150,0.0
561,1.0,0.50,1.0,0.5,0.0,0.000000,0.050,1.0
562,0.0,0.50,1.0,0.5,0.0,0.333333,0.150,1.0
...,...,...,...,...,...,...,...,...
5337,0.0,0.25,0.0,0.5,0.0,0.000000,0.150,1.0
5338,0.0,0.75,1.0,0.5,0.0,0.000000,0.050,1.0
5339,0.0,0.75,0.0,0.5,0.0,0.000000,0.075,1.0
5340,0.0,0.25,0.0,0.5,1.0,0.000000,0.150,1.0
5341,0.0,0.25,0.0,0.5,0.0,0.000000,0.050,0.0

In [64]:
# Gender imbalance

round(data_num_scaled_reduced["gender"].value_counts()[0] / (data_num_scaled_reduced["gender"].value_counts()[0] + data_num_scaled_reduced["gender"].value_counts()[1]) * 100, 2)

87.9

## Machine learning (preparation)

### X-y split

In [65]:
X = data_num_scaled_reduced.drop(columns="final_result")
y = data_num_scaled_reduced["final_result"]

In [66]:
# Positive class imbalance

round(y.value_counts()[1] / (y.value_counts()[1] + y.value_counts()[0]) * 100, 2)

63.46

### Train-test split

In [67]:
# Choose a train-test split

user_response2 = input("Do you want 70-30 or 80-20 train-test split? (Write either 7030 or 8020.)")
if user_response2 == "7030" or user_response2 == "8020":
    SPLIT = user_response2
else:
    print("Invalid choice.")
    exit()

In [68]:
pickle.dump(SPLIT, open("../data/SPLIT", "wb"))

In [69]:
if SPLIT == "7030":
    ratio = 0.30
elif SPLIT == "8020":
    ratio = 0.20

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=0, stratify=y, shuffle=True)

In [71]:
pd.DataFrame(X_train).to_csv("../data/X_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(X_test).to_csv("../data/X_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_train).to_csv("../data/y_train" + "_" + DATA + "_" + SPLIT + ".csv", index=False)
pd.DataFrame(y_test).to_csv("../data/y_test" + "_" + DATA + "_" + SPLIT + ".csv", index=False)

In [72]:
print(X_train.shape)
print(X_test.shape)

(3348, 7)
(1436, 7)