In [1]:
"""
Created on: Fri. 5 Aug. 2022
Updated on: Tue. 9 Aug. 2022
Updated on: Tue. 23 Aug. 2022
Updated on: Mon. 29 Aug. 2022
Updated on: Wed. 31 Aug. 2022
Updated on: Fri. 30 Sep. 2022
Updated on: Wed. 12 Oct. 2022
Updated on: Fri. 6 Jan. 2023
Author: Mélina Verger

Display stAll.
"""

# For data manipulation
import pandas as pd

In [2]:
stAll = pd.read_csv("../data/studentAll.csv")

In [3]:
stAll

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,sum_click,weighted_score,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,0,240,934,82.400000,Pass
1,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,0,240,934,82.400000,Pass
2,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,0,240,934,82.400000,Pass
3,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,0,240,934,82.400000,Pass
4,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,0,240,934,82.400000,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26584,GGG,2014J,2620947,F,Scotland,A Level or Equivalent,80-90%,0-35,Y,0,30,476,88.888889,Distinction
26585,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,N,0,30,893,88.111111,Distinction
26586,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,Y,0,30,312,76.666667,Pass
26587,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,N,0,30,275,91.500000,Withdrawn
26588,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,N,0,30,616,82.857143,Distinction

In [4]:
len(stAll["id_student"].unique())

23344

In [5]:
stAll.isna().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1030
age_band                   0
disability                 0
num_of_prev_attempts       0
studied_credits            0
sum_click                  0
weighted_score             0
final_result               0
dtype: int64